### ISSUE TITLE
Investigate removing build date requirement from front-end charting

### ISSUE THREAD

**Issue by robhudson** [mozilla/glam#1113]
Right now we require a date from the data from the ETL in order to chart aggregations by build ID. The ETL does not have this requirement and can aggregate against any consistently sortable string for a build ID.

Since we chart aggregations by version, which are not tied to a date, it seems reasonable to assume that we could also chart by build ID without a date as well. I suspect the date requirement was an early code assumption. We should look into what it would take to remove this requirement to make it easier to add more Glean products that don't embed some encoded date into the build ID.

**Comment by rafrombrc** [comment]
Rob Hudson looked into this, estimate is removing this assumption will take ~1 week of work. We almost certainly will always want to know the date associated w a build, so we're going to take the approach of pushing date info through the w the build id and the ETL rather than doing this work, unless we absolutely have to.
