### ISSUE TITLE
Ability to zoom into a range in the past

### ISSUE THREAD

**Issue by mstange** [mozilla/glam#1127]
At the moment, the history view allows selecting the following time horizons: Week, Month, Quarter, All
These are all about the *most recent* week/month/quarter.

But what if I want to take a closer look at something that happened 6 months ago? I cannot view "a week during Firefox 80", for example.
It would be great to just be able to select a range by dragging the mouse, and zoom to that range. (And also have that range reflected in the URL so that the URL can be shared.)

**Comment by robhudson** [comment]
Update: This has been deployed to production.

The ability to zoom is tied to the reference point (left clicking on the chart) and the hover point (the point that follows the mouse). When right-clicking a context menu will open that will show the range (from hover to ref point) and the ability to zoom in on that range.

![zoom-to-range](https://user-images.githubusercontent.com/1106/112521904-43437700-8d5a-11eb-8ae5-d1a15124a2d5.png)

Just a note: It was decided to implement this as a right-click context menu versus, say, a scrub UI where you drag the mouse along the range, due to time constraints as this was quicker to implement to get out to users. We may revisit the UI in the future.
