### ISSUE TITLE
Can't view Glam data for probes added last week

### ISSUE THREAD

**Issue by jesup** [mozilla/glam#1753]
I'm trying to view the Glam data for service_worker_running and serviceworker_running_max.  These are viewable on the older Telemetry (example: https://mzl.la/31P6w6S).   Glam times out after 30s every time (I've tried a dozen+ times over the last hour, and I also tried a few times last night).

Devtools tells me that the request is getting a 502 after ~30s:
502 on https://glam.telemetry.mozilla.org/api/v1/data/  limit=undefined
select=name%2Cdescription%2Ctype%2Cinfo
type=neq.event
or=%28name.eq.service_worker_running%29
not.and=%28type.eq.scalar%2Cinfo-%3Ecalculated-%3Elatest_history-%3Edetails-%3E%3Ekind.eq.string%29
order=info-%3Ecalculated-%3E%3Eactive.desc

**Comment by Iinh** [comment]
Thank you for reporting this @jesup. We're looking into it right now.

**Comment by emtwo** [comment]
@jesup: for the time being, the probes seem to be loading in the staging environment: https://stage.glam.nonprod.dataops.mozgcp.net/firefox/probe/serviceworker_running_max/explore?process=parent

**Comment by rafrombrc** [comment]
Okay, we've been digging in here... we figured out that a recent ETL change contains a bug that blew up the size of our data sets, which caused the GLAM queries to run so slowly that they were timing out. We've reverted the ETL change and have deleted the recently imported data so GLAM is no longer timing out. Your probes are now returning "404: No data found for the selected dimensions" instead of timing out because they're new probes, so deleting the recently imported data cleared them out entirely.

We're now re-running the ETL / data import process with the reverted ETL code, we expect that when this completes the probes should show the data as expected. We'll update this issue again when the data is available.

**Comment by alekhyamoz** [comment]
Hi @jesup, the issue has been resolved and we can now see the data for service_worker_running and serviceworker_running_max in desktop nightly category
<img width="1629" alt="Screen Shot 2021-12-16 at 12 11 40 PM" src="https://user-images.githubusercontent.com/88394696/146417388-1d890c26-f9de-4b73-a62c-f23da3923b3a.png">
<img width="1599" alt="Screen Shot 2021-12-16 at 12 12 12 PM" src="https://user-images.githubusercontent.com/88394696/146417478-f2b4f5b3-613a-47a0-b2e2-ba18ca9d7338.png">

Please let us know if you have any further questions.
