### ISSUE TITLE
GLAM throws network error for some probes though data exists in backend tables(eg: sqlite_store_open)

### ISSUE THREAD

**Issue by alekhyamoz** [mozilla/glam#1841]
GLAM throws a network error when accessing some probes : 
Eg: sqlite_store_open / sqlite_store_query 

<img width="1265" alt="Screen Shot 2022-02-18 at 2 29 45 PM" src="https://user-images.githubusercontent.com/88394696/154749254-cdcf6eb3-6dcd-43d2-a173-1fb926e18820.png">

https://glam.telemetry.mozilla.org/firefox/probe/sqlite_store_open/explore?channel=release&os=Mac&process=parent
https://glam.telemetry.mozilla.org/firefox/probe/sqlite_store_query/explore?channel=release&process=parent 

Another example of keyed-scalar-boolean:
https://glam.telemetry.mozilla.org/firefox/probe/browser_ui_toolbar_widgets/explore?channel=release&os=Mac&process=parent

I have verified that the data related to this probe exists in the postgres table. 

<img width="1729" alt="Screen Shot 2022-02-18 at 2 29 15 PM" src="https://user-images.githubusercontent.com/88394696/154749178-d7fb43e8-a8f4-4f37-8fcc-67896a22d0a2.png">

**Comment by Iinh** [comment]
Locally data is fetched successfully for these probes. We need to investigate why we're getting 502 server errors in production.

**Comment by edugfilho** [comment]
Ongoing investigation: Here's the amount of distinct ip addresses that got errors in the last two weeks, and the probes that caused it.
Looking at how different parameter combinations affect this 

![Screen Shot 2022-02-23 at 5 33 47 PM](https://user-images.githubusercontent.com/5804462/155420715-a70aabd8-31c0-4f44-88a7-1ffd79ba0c32.png)

**Comment by edugfilho** [comment]
Big chance this (or at least one of the problems) is being caused by gunicorn running out of memory while processing large probe payloads:
- It works locally, but not while deployed 
    - Checking locally, some payloads are over 100MB
    - Checking the prod cluster, looks like each pod has only 100MB of memory (edit: 100MB requested, but 500MB limit)
- Looking at live app logs on GKE (BQ only has Load Balancer logs, which aren't very telling for this problem) I found the following error while searching `sqlite_store_open` on GLAM: 
     `[WARNING] Worker with pid <pid> was terminated due to signal 9` <- this is a gunicorn error
     - Signal 9 is SIGKILL, but one very common cause for it is the process ran OOM, especially in gunicorn
     
My next steps:
- Change the memory config on my local docker environment to 100MB and test/debug
- Look at live app logs for other failing probes

**Comment by edugfilho** [comment]
Still working on replicating the problem locally, but at this point I'm pretty confident container memory is one issue. This is from[ GKE Pod Details:](https://console.cloud.google.com/kubernetes/pod/us-west1/glam-prod-v1/prod-glam/glam-prod-glam-app-1-7c6ddc8d9-7xrdr/details?cloudshell=false&project=moz-fx-data-glam-prod-fca7&supportedpurview=project)  

![Screen Shot 2022-02-24 at 11 55 31 AM](https://user-images.githubusercontent.com/5804462/155570961-610f8a90-865f-4a27-b9a5-db8ffa0acafb.png)

**Comment by edugfilho** [comment]
Executing the GLAM SQL of probes on BQ
Probes that cause server error:
* `sqlite_store_open` -> produces 2GB of data
* `browser_ui_toolbar_widgets` -> 157MB (this one went to the canary pod (why?) but doesn't spike mem to the limit)
* `sqlite_store_query` -> 104.67 GB (huge resultset, also went to canary, caused spike to limit)

Now`browser_engagement_active_ticks` has zero Bytes reported by BQ (only 230 rows). Very likely to be a different problem

**Comment by alekhyamoz** [comment]
Please ignore the `browser_engagement_active_ticks` as the issue was caused due to SSO session timeout. 
I can see the data for this probe now

**Comment by edugfilho** [comment]
I was able to reproduce the error locally by limiting container memory in the docker-compose file, ran a number of tests and here's what I learned:
- The GLAM Server containers need at least 2GB of memory to be able to serve `sqlite_store_query`. Otherwise they die out of memory 
  - This behavior is different in prod, where the gunicorn thread gets killed instead of the container. I think it's just the way the Kubernetes application is configured in prod
  
- Even with 2GB of memory available to them, after a handful of `sqlite_store_query` requests, give or take, the container dies and the UI gets a `NetworkError when attempting to fetch resource`

Will run some more tests locally with logging in debug mode

**Comment by edugfilho** [comment]
Docker killing the container bc it runs OOM:
<img width="545" alt="Screen Shot 2022-02-25 at 1 11 46 PM" src="https://user-images.githubusercontent.com/5804462/155766192-a3834204-8f78-4049-ab24-a1d683e61910.png">

Took me some time to set this up, but once I could get VSCode running on debug mode attached to Docker, I could confirm this happens when [the query result is being iterated over and a response object is being built](https://github.com/mozilla/glam/blob/37d9f8b3118085201b5a27250ddb5f0e776f92d5/glam/api/views.py#L114)

I would say in the meantime we could also increase container memory limit in staging/prod environments, but without understanding much about the data and given that those probes' results are such outliers, I really want to see if there's something we can do before that. So my plan now is to better understand `sqlite_store_query` and the other probes that crash the app and see why they get so big and if there's something we can do about it (truncate, filter...) to prevent the error. @alekhyamoz @Iinh in case you're familiar with the data, let me know if you have any ideas.

**Comment by alekhyamoz** [comment]
I have attached a file that gives the number of keys for each probe. 
We can see that some probes have a high number of keys specially 
```
sqlite_store_open
sqlite_store_query
browser_ui_interaction_content_context
``` 

Tried `network_http_redirect_to_scheme`, as an example, which has a relatively lesser number of keys and it works
I would suspect that a high volume of key-metric data might be causing the issue. 
At this point, I am not very sure who are the users/consumers of these probes' data. 
Maybe instrumentation will help us figure this out. 


[numberofkeys_for_each_probe.csv](https://github.com/mozilla/glam/files/8144110/numberofkeys_for_each_probe.csv)

**Comment by edugfilho** [comment]
Thanks @alekhyamoz for clarifying some aspects of the data,  here's the problem behind the `sqlite_store_*`  and  `browser_ui_toolbar_widgets`:

The `sqlite_store_*`  probes represent the result of the browser querying/opening a sqlite file, and their `key`s are  **sqlite file names**, which means we're storing a key for every file name, and file names can be anything with a `.sqlite` extension. Right now we have over 115M distinct key names for `sqlite_store_open` (Release, any OS).

Similarly, for the `browser_ui_toolbar_widgets` the key is the **widget name**, and by taking a look at a sample of those keys it seems they have all sorts of weird names. I suppose this is because users install extensions that add widgets to the browser's toolbar? For this probe we "only" have 49K keys, which is only a fraction of the `sqlite_store_open`, but nonetheless still too many for a manual key selection on GLAM's UI

So my thoughts now are that the probes in question are just too noisy to be useful to anybody and the data shows nobody comes to see them. With that in mind I think we should probably stop calculating them and communicate that "issue" with the team responsible for them, just to make sure this is intended.
  * An alternative to stop calculating the probes could be replacing the file/widget name as a key with something more meaningful and less noisy such as file size for sqlite (just an example, I really don't know) or making the `key` field mandatory on GLAM so we narrow the search (also not sure how useful it would be, need to assess the UI/Backend effort and see if it's worth it)
  * In case we decide to stop calculating the probes, when we have the GLAM Instrumentation mechanism working, which will hopefully indicate those probes are not being used therefore don't need to be precalculated, we'll also need to prevent ad-hoc calculation for them, and signal to users that we don't offer such data.

**Comment by edugfilho** [comment]
We communicated the issue with the sqlite_store_* probes to the owners (Dave Townsend and Marco Bonardo) and it's currently being discussed in a email thread.

@rafrombrc just confirming: Do we wait for an outcome of the discussion or do we move on with this by removing the calculation of probes from the ETL like we discussed? In the latter case I'll close this issue and create an issue on bigquery-etl for stop calculating the probes, and another one here for deleting those probes' data from GLAM's cloudsql.

**Comment by rafrombrc** [comment]
That's a good question. I'd say let's let them know that this is causing us operational pain, so we want to take _some_ action ASAP, and see if they're okay w us removing the probes from GLAM until they get it resolved. We can probably backfill the data after they get the probe fixed up, although we'd need to munge the data a bit to merge all of the unique filenames into whatever single key they choose to use.

**Comment by edugfilho** [comment]
Tracking this issue on #1865 
Closing

**Comment by Iinh** [comment]
We're running into a similar issue with [browser_ui_interaction_content_context](https://glam.telemetry.mozilla.org/firefox/probe/browser_ui_interaction_content_context/explore?channel=release&currentPage=1&process=parent), though the server error is intermittent. Also see [DSRE-972](https://mozilla-hub.atlassian.net/browse/DSRE-972) current SRE response.
