### ISSUE TITLE
VIDEO_DROPPED_DECODED_FRAMES_PROPORTION_EXPONENTIAL missing from GLAM

### ISSUE THREAD

**Issue by jrmuizel** [mozilla/glam#1914]
This probe, as well as VIDEO_DROPPED_SINK_FRAMES_PROPORTION_EXPONENTIAL and VIDEO_DROPPED_COMPOSITOR_FRAMES_PROPORTION_EXPONENTIAL were added a number of days ago in https://hg.mozilla.org/mozilla-central/rev/ac698a0182d7

**Comment by badboy** [comment]
This is a bug in probe-scraper. New probes are currently not scraped from the repository. See https://github.com/mozilla/probe-scraper/pull/412

**Comment by Iinh** [comment]
Hi @jrmuizel, this issue is now fixed (thanks for your patience)! See the below links for these probes:

- https://glam.telemetry.mozilla.org/firefox/probe/video_dropped_decoded_frames_proportion_exponential/explore?currentPage=1
- https://glam.telemetry.mozilla.org/firefox/probe/video_dropped_sink_frames_proportion_exponential/explore?currentPage=1
- https://glam.telemetry.mozilla.org/firefox/probe/video_dropped_compositor_frames_proportion_exponential/explore?currentPage=1
