### ISSUE TITLE
Interpolate bucket values on chart for more intuitive interpretation

### ISSUE THREAD

**Issue by edugfilho** [mozilla/glam#2054]
Suggested by Bas during interview.
When percentile values oscillate around the edge of their buckets over time it makes the chart show frequent small spikes like the one below. According to Bas, this is harder to parse compared to a smooth, interpolated transition from one bucket to another. We should check with Data Science the right way to do bucket interpolation and, if any, the trade-offs of such change. 

![Screen Shot 2022-07-13 at 1 11 53 PM](https://user-images.githubusercontent.com/5804462/178792534-ef7c1720-93cf-4c2a-9fa3-f4b4da55a968.png)

**Comment by Iinh** [comment]
What do you think about this @perrymcmanis144?

**Comment by perrymcmanis144** [comment]
My intuition is that between "leave as is" and "interpolate" it might unfortunately be preferable to leave as is. But those are the extreme examples. Interpolating potentially creates a delay in seeing changes and adds a layer of complexity to the interpretation. That said, I do not think it is a bad idea if there were an option to select a 'smoothed' version and a 'real time' version.

Is it fair to assume this is either a display or at worst a view option? I would strongly advise _against_ any changes to base tables even if that would preclude any interpolation. Seems exceptionally unlikely but worth stating explicitly. That aside, the tradeoff of smoothing is then a matter of how fast you see a real change in data versus a less jarring experience and the potential to mistake single day changes.

Looking at the visual provided, I would be amenable to doing a moving average of the past few days as a clickable option and maybe label these along the lines of "smoothed" and "actual". Given the size of the changes, perhaps even 3 days would be adequate. I don't think it's necessarily worthwhile to explore making logical decisions on the values themselves unless that's genuinely the only way; values are what they are and percentiles are as well subsequently, and applying post-observation correction is not really the solution IMO (greater scale such that you converge to the "true" distribution would be). SO I do not believe there is a case for _that_ level of correction, but I definitely do see the merit in addressing Bas' visualization concern.

I would also suggest that flattening the histograms would be reasonable if there is a desire to see the true distribution rather than the result of changes. I.E. for metrics that should not change, each day would add the observations to the entire set, so rather than each day being that day's distribution, it would be the distribution of the ENTIRE period. Seems like overkill though.

As a tl;dr, a small moving average as a visualization option seems like a good compromise to me.

Happy to discuss further; please let's leave the _needs DS support_ tag for the time being.

**Comment by jonco3** [comment]
I came up against this trying to get stable values for median GC_MS time from GLAM. I'm looking an unnormalized data for nightly and it is telling me it's either 47ms or 58ms depending on which day I look at. That's a difference of > 20%. This is an issue when trying to asses the impact of changes where improvement or regression may be much smaller than that amount.

![Screenshot 2024-01-29 at 16-16-52 gc_ms GLAM](https://github.com/mozilla/glam/assets/861138/a073b978-28d5-43f9-af12-c91d2a55c393)

**Comment by jonco3** [comment]
While a moving average might help, I think the answer here is not to use an average over several days but to use an interpolation method when calculating the percentiles for a single day. With ~10M samples per day for nightly we should have enough data to generate a more accurate result. The [wiki page](https://en.wikipedia.org/wiki/Percentile) lists some methods but as mentioned above Data Science would know best.
