### ISSUE TITLE
Probe labeled as inactive

### ISSUE THREAD

**Issue by tomrittervg** [mozilla/glam#2067]
I [put these probes in a few releases ago](https://searchfox.org/mozilla-central/rev/1061fae5e225a99ef5e43dbdf560a91a0c0d00d1/dom/base/UseCounters.conf#123-125).  Neither one of them has any data in GLAM, and one is labeled as inactive.  Neither probe appears in tmo either.  

I'm not sure why they have no data (I have to imagine _one person_ has used this feature in the past several releases) nor do I understand why one is labeled as inactive but not the other.

**Comment by Iinh** [comment]
Hi @tomrittervg, just checking if I understand your question correctly. Are these the 2 probes in question? 

- [use_counter2_xslstylesheet_document](https://glam.telemetry.mozilla.org/firefox/probe/use_counter2_xslstylesheet_document/explore?activeBuckets=%5B%22no%22%2C%22yes%22%5D&currentPage=1)
- [use_counter2_xslstylesheet_page](https://glam.telemetry.mozilla.org/firefox/probe/use_counter2_xslstylesheet_page/explore?activeBuckets=%5B%22no%22%2C%22yes%22%5D&channel=beta&currentPage=1&process=parent)


If yes, it seems they are both labeled active now. While GLAM does have data for these probes on `beta` and `release`, I can see that there is no data for nightly.

I suspect this is because we don't have _enough_ data, as the ETL does require the probe to have [more than 375 `client_id`s in nightly](https://github.com/mozilla/bigquery-etl/blob/d9e0c2abaab6feb13b7bde47a9493fa91013d880/sql/moz-fx-data-shared-prod/telemetry_derived/clients_histogram_bucket_counts_v1/query.sql#L66-L69).

**Comment by tomrittervg** [comment]
That is one of the probes, [the first one](https://searchfox.org/mozilla-central/rev/c2a2bf5a49626d63c4c0a5be42b6a93838c1b595/dom/base/UseCounters.conf#124).  The pages for these are concerning - there isn't a single 'Yes' report.  Is that to be believed?

Here is the other one: [one](https://glam.telemetry.mozilla.org/firefox/probe/use_counter2_xsltprocessor_constructor_document/explore?activeBuckets=%5B%22no%22%2C%22yes%22%5D&channel=release&currentPage=1&proportionMetricType=counts&timeHorizon=QUARTER), [two](https://glam.telemetry.mozilla.org/firefox/probe/use_counter2_xsltprocessor_constructor_page/explore?activeBuckets=%5B%22no%22%2C%22yes%22%5D&channel=release&currentPage=1&process=parent&proportionMetricType=counts&timeHorizon=QUARTER).  These don't seem to have any data at all?

**Comment by Iinh** [comment]
Thanks for your patience. Here is my investigation so far.

To provide more clarity why some probes are labeled `inactive`, even when they have not expired. GLAM marks a probe as inactive when we don't see enough data. Specifically, if we don't see at least 0.5% of weekly active users for a build, we don't aggregate that probe. This was designed to make it hard for respins and other low-volume build ids to accidentally appear in the dataset.

Now back to your questions.

> Here is the other [one](https://glam.telemetry.mozilla.org/firefox/probe/use_counter2_xsltprocessor_constructor_document/explore?activeBuckets=%5B%22no%22%2C%22yes%22%5D&channel=release&currentPage=1&proportionMetricType=counts&timeHorizon=QUARTER): one, [two](https://glam.telemetry.mozilla.org/firefox/probe/use_counter2_xsltprocessor_constructor_page/explore?activeBuckets=%5B%22no%22%2C%22yes%22%5D&channel=release&currentPage=1&process=parent&proportionMetricType=counts&timeHorizon=QUARTER). These don't seem to have any data at all?

[This query](https://sql.telemetry.mozilla.org/queries/87113/source) returns `client_count_with_data` = 0 for the last week. This means all we received for this prove so far is NULL, and that's strange. Usually when this happens it's because there's something wrong with the probe implementation. Could you double check how the probe is implemented, as I'm not familiar with this one.

> That is one of the probes, [the first one](https://searchfox.org/mozilla-central/rev/c2a2bf5a49626d63c4c0a5be42b6a93838c1b595/dom/base/UseCounters.conf#124). The pages for these are concerning - there isn't a single 'Yes' report. Is that to be believed?

GLAM sources data from the [main ping](https://docs.telemetry.mozilla.org/datasets/main_ping_tables.html) table. I ran [the telemetry SQL in STMO](https://sql.telemetry.mozilla.org/queries/87182/source) and it seems to confirm what we see in GLAM.

**Comment by Iinh** [comment]
We were able to confirm this is not a GLAM issue. `use_counter2_xsltprocessor_constructor` probes are not being triggered correctly hence the NULL data, which led to them being marked as inactive. Further digging is needed to really understand whether there's something to be done about the specific implementation of this probe, or  `use_counter2` mechanism. These separate issues will be raised with the Data Collection team.
