### ISSUE TITLE
Categorical histogram view doesn't show labeled values

### ISSUE THREAD

**Issue by wlach** [mozilla/glam#882]
GLAM's enumerated histogram view (https://glam-stage.bespoke.nonprod.dataops.mozgcp.net/firefox/probe/update_notification_shown/explore?activeBuckets=%5B%222%22%2C%220%22%2C%221%22%2C%223%22%2C%224%22%2C%225%22%2C%226%22%2C%227%22%2C%228%22%2C%229%22%5D&aggregationLevel=build_id&channel=release&os=Windows&process=parent&proportionMetricType=proportions&timeHorizon=MONTH&visiblePercentiles=%5B95%2C75%2C50%2C25%2C5%5D) answered somebody's question today in #data-help (which is awesome), but it was a bit more confusing than need be because it didn't use the labels included with the probe (`update_notification_shown`). This appears to be a regression from the old telemetry dashboard.

![image](https://user-images.githubusercontent.com/20569/93125066-9ac0a600-f698-11ea-83d0-ff25b9252340.png)

Link to thread while it lasts: https://mozilla.slack.com/archives/C4D5ZA91B/p1600092198084100

**Comment by chutten** [comment]
To be a _little_ pedantic, this is for "categorical" histograms (where the labels are in a known machine-readable format (the `labels` property)) which are distinct from "enumerated" histograms (where the labels are unknown unless you dive into the description, the source, or history). There's sadly nothing we can do about histograms with the "enumerated" kind beyond continuing to ask data owners to move to "categorical" histograms because they're better for analysis.
