### ISSUE TITLE
Fix axis label and table overflows on certain pages

### ISSUE THREAD

**Issue by rafrombrc** [mozilla/glam#923]
Visible [here](https://glam-dev.bespoke.nonprod.dataops.mozgcp.net/fenix/probe/performance_time_dom_interactive/explore?activeBuckets=%5B%5D&aggregationLevel=version&app_id=beta&os=Android&ping_type=metrics&proportionMetricType=proportions&reference=82&timeHorizon=ALL_TIME&visiblePercentiles=%5B95%2C75%2C50%2C25%2C5%5D)

**Comment by robhudson** [comment]
The goal is to use Glean's units, when available, to something more human readable. For example, instead of `168,000,000,000 nanoseconds`, display `2.8 seconds`.

Extra info:

The metric types that support unit-like fields are `Timespan`, `Timing Distribution`, `Memory Distribution`, `Custom Distribution`, and `Quantity`. `Custom Distribution` and `Quantity` are not expected to have values that are useful for the formatting of digits. They may have something like "Pixels squared per millisecond" or "tabs".

`Timespan` and `Timing Distribution` both have `time_unit` which has a set number of acceptable values that we control via `glean_parser validation`, so are very suitable for the formatting of digits. `Memory Distribution` similarly, for `memory_unit`.

The rest of the metric types are unitless.
