### ISSUE TITLE
Separate Firefox release markers from Fenix release markets

### ISSUE THREAD

**Issue by robhudson** [mozilla/glam#955]
In other words, make the FIrefox release markers product specific only to Firefox.

**Comment by robhudson** [comment]
It was decided that we will keep the Firefox release markers for Fenix since gecko view roughly tracks Firefox Desktop and there's currently no good source of release info for Fenix (see https://bugzilla.mozilla.org/show_bug.cgi?id=1622948).

This issue has been updated to separate the code that drives the release markets to be per-product so in the future when we do have more accurate release data we can easily drop it in without affecting other products.

**Comment by edugfilho** [comment]
Hi! 
Sorry I don't speak front-end really well so I'm trying to understand the changes we want to make. I noticed the release markers are implemented in [FirefoxReleaseVersionMarkers.svelte](https://github.com/mozilla/glam/blob/9dec1a85e8b3a9cc861d108db236f36283a4161c/src/components/FirefoxReleaseVersionMarkers.svelte#L17), and that that component gets its data from [product-versions.js](https://github.com/mozilla/glam/blob/9dec1a85e8b3a9cc861d108db236f36283a4161c/src/state/product-versions.js#L47), which makes a call to [product-details.mozilla.org](https://product-details.mozilla.org/1.0/all.json). Now my questions are:

- Is there backend involved into this? (I see the tag `backend` and wondered if I'm missing something)
- If no backend, then what we want to do is basically make copies of [FirefoxReleaseVersionMarker](https://github.com/mozilla/glam/blob/9dec1a85e8b3a9cc861d108db236f36283a4161c/src/components/FirefoxReleaseVersionMarkers.svelte#L1) and [firefoxVersionMarkers](https://github.com/mozilla/glam/blob/9dec1a85e8b3a9cc861d108db236f36283a4161c/src/state/product-versions.js#L47) and rename it for Fenix, so we can customize it independently when we have appropriate Fenix release data?

**Comment by Iinh** [comment]
> Is there backend involved into this?

No, there shouldn't be, because we're only changing the code logic inside the component to be per `$store.product`. Per @robhudson 's comment:

> This issue has been updated to separate the code that drives the release markets to be per-product so in the future when we do have more accurate release data we can easily drop it in without affecting other products.

`backend` tag is removed.


> If no backend, then what we want to do is basically make copies of [FirefoxReleaseVersionMarker](https://github.com/mozilla/glam/blob/9dec1a85e8b3a9cc861d108db236f36283a4161c/src/components/FirefoxReleaseVersionMarkers.svelte#L1) and [firefoxVersionMarkers](https://github.com/mozilla/glam/blob/9dec1a85e8b3a9cc861d108db236f36283a4161c/src/state/product-versions.js#L47) and rename it for Fenix, so we can customize it independently when we have appropriate Fenix release data?


That sounds good! Another way to implement this could be:

- change `FirefoxReleaseVersionMarker `name to something more generic, like `ReleaseVersionMarker`
- in `ReleaseVersionMarker` component, add a condition statement to check what the current product is and then apply the relevant logic. For example, because currently firefox and fenix are sharing the same release data:

```
if (["firefox", "fenix"].includes($store.product) then (the current code)...
<g class="firefox-release-version-markers">
  {#if markers && markers.length}
....
```

Something like this. Once we have more accurate Fenix release data, or when we need to add other products, it should be straightforward to extend the logic here. 

Hope that makes sense. I'll leave it to you to decide how to implement it.

**Comment by edugfilho** [comment]
Clear and thorough. Thank you so much for this, Linh!
